### ISSUE TITLE
Merging bin_100kb.rds files

### ISSUE THREAD

**Issue by stephensammut** [cancer-genomics/delfi_scripts#2]
Hi,

I'm trying to run DELFI, and came across a missing bit of code.

File **03-bin_compartments.r** processes multiple *frags.rds files generated by **02-fragment_gc.r** into multiple *bin_100kb.rds files.

However the input to the subsequent R script, **04-5mb_bins.r**, appears to be a summarised version of these *bin_100kb.rds files:

`df.fr <- readRDS("../inst/extdata/bins_100kbcompartments.rds")
`

Would you be able to tell me how you merged the multiple bin_100kb.rds files into one bins_100kbcompartments.rds file please, as this is not included within the scripts?

Thanks!

**Comment by Jingjiao-ma** [comment]
Hi，

I also have the same problem. Have you solved it?

Thanks！

**Comment by stephensammut** [comment]
Has any progress been made regarding this issue please?

**Comment by dmaloneynygc** [comment]
In addition to this, can you provide the code use to generate the zscores in 'sample_reference.csv' which looks to be the zscores for the chromosome-arm copy number analysis?

Also where is "../inst/extdata/summary_tibble.rds" coming from? What is it?

**Comment by rscharpf** [comment]
Please see 03.5-combine_bins.r that addresses the merging issues
