### ISSUE TITLE
the question of merging 100bk bins into 5M of script 4

### ISSUE THREAD

**Issue by WellJoea** [cancer-genomics/delfi_scripts#3]
Hi:
   the script 3, 03-bin_compartments_v1.r, use the 100bk bins to compute the shot and long  counts by  
modules "findOverlaps" and "countOverlaps". 
 The modules count each reads twice that span the adjacent two bins. So in the script 4 04-5mb_bins.r，I confused whether there is problem derectly using the sum statistical results to merge 100kb into  5M bins. 
Is it neceessary to recount  shot and long  counts by merging the bings into 5M in script 3？

 Also, I cannot find the file ""../inst/extdata/bins_100kbcompartments.rds".

**Comment by rscharpf** [comment]
Please see 03.5-combine_bins.r.
