### ISSUE TITLE
data access

### ISSUE THREAD

**Issue by miaomiaozhou88** [cancer-genomics/delfi_scripts#6]
Dear author,

A month ago, we contacted Jillian Phallen <jphalle2@jhmi.edu> and sent her our data usage agreement with the signature of our dean. however, we still did not hear anything about the data. On the EGA page we still don't have access to download the data. 

Would you please let us know what else should be done? The purpose is pure academic. 

With kind regards, School of Life Sciences, Avans university of applied sciences, Breda.

**Comment by biubiu-1** [comment]
I wonder if you have solved this problem? It seems the data accession ID hasn't been updated yet.

**Comment by cvaske** [comment]
I have been able to gain access through EGA through that email address, and have downloaded most of the data.  I used the email address above, and it took some time but finally happened.  Downloading from EGA has been very slow, as individual files stream very slowly and need many restarts as they time out. But one of these days, all the data should be downloaded...
