### ISSUE TITLE
Script 04-5mb_bins.r

### ISSUE THREAD

**Issue by tarens98** [cancer-genomics/delfi_scripts#8]
Hi,

We, students of Avans Breda, are trying to run DELFI and came across some errors resulting from running script 04 that we don't understand. For example:

Error in UseMethod("inner_join") :
  no applicable method for 'inner_join' applied to an object of class "c('GRanges', 'GenomicRanges', 'Ranges', 'GenomicRanges_OR_missing', 'GenomicRanges_OR_GenomicRangesList', 'GenomicRanges_OR_GRangesList', 'List', 'Vector', 'list_OR_List', 'Annotated', 'vector_OR_Vector')"
Calls: inner_join

It seems that our output file from script 03 can't be used together with the sample_reference.csv file in the inner_join function. Also, when we look in to the output file of script 03 (ourfilespecification_frags_bin_100kb.rds) we can't find the header 'sample' that the the 04 script seems to be looking for within these lines (for example):

df.fr <- readRDS("../.../.../ourfilespecification_frags_bin_100kb.rds")
master <- read_csv("sample_reference.csv")

df.fr2 <- inner_join(df.fr, master, by=c("sample"="WGS ID"))

hic.eigen <- (df.fr2 %>% filter(sample=="PGDX10346P1"))$hic.eigen
 
Could you help us understand this error message and how to solve it?
We look forward to your response at your earliest convenience.

With kind regards, School of Life Sciences, Avans university of applied sciences, Breda.

**Comment by tarens98** [comment]
If we try to turn the input data for script 04 into a dataframe object the next error gets generated:

Error: `by` can't contain join column `sample` which is missing from LHS
Backtrace:
     █
  1. ├─dplyr::inner_join(df.fr, master, by = c(sample = "WGS ID"))
  2. └─dplyr:::inner_join.data.frame(df.fr, master, by = c(sample = "WGS ID"))
  3.   ├─base::as.data.frame(...)
  4.   ├─dplyr::inner_join(tbl_df(x), y, by = by, copy = copy, ...)
  5.   └─dplyr:::inner_join.tbl_df(...)
  6.     ├─dplyr::common_by(by, x, y)
  7.     └─dplyr:::common_by.character(by, x, y)
  8.       └─dplyr:::common_by.list(by, x, y)
  9.         └─dplyr:::bad_args(...)
 10.           └─dplyr:::glubort(fmt_args(args), ..., .envir = .envir)
Execution halted

Which makes it clear again that not being able to find 'sample' is a problem

**Comment by rscharpf** [comment]
We have added `03.5-combine_bins.r` to address the issue raised here.
